server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  mustache:
    charset: UTF-8
    content-type: text/html
    prefix: classpath:/templates/
    suffix: .html


  security:
    oauth2:
      client:
        registration:
############# google login #############
          google:
            client-id: 10166727975-pt9iejc3bpf3ltivgo68i011om2t57jk.apps.googleusercontent.com
            client-secret: bi-y3YpGgQWZbygNS-SrX02S
            scope:
            - profile
            - email
############# facebook login #############
          facebook:
            client-id: 894149768185960
            client-secret: 35377e5b604eb668aabb5f4a398fb25f
            scope:
              - email
              - public_profile
############# naver login #############
          naver:
            client-id: CF6fjZ3R83vAH2B6Pbwm
            client-secret: vh9yinzVDj
            scope:
              - email
              - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost/login/oauth2/code/naver

        provider:
          naver:
           authorization-uri: https://nid.naver.com/oauth2.0/authorize
           token-uri: https://nid.naver.com/oauth2.0/token
           user-info-uri: https://openapi.naver.com/v1/nid/me
           user-name-attribute: response #회원정보를 json 으로 받는데 response 라는 키값으로 네이버가 리턴해줌.




